CREATE DATABASE THITHU2
USE THITHU2
GO

CREATE TABLE NHANVIEN
(
	MANV CHAR(5),
	HOTEN VARCHAR(20),
	NGAYVL SMALLDATETIME,
	HSLUONG NUMERIC (4,2),
	MAPHONG CHAR(5),
	PRIMARY KEY (MANV),
	FOREIGN KEY (MAPHONG) REFERENCES PHONGBAN(MAPHONG)
)

CREATE TABLE PHONGBAN
(
	MAPHONG CHAR(5),
	TENPHONG VARCHAR(20),
	TRUONGPHONG CHAR(5),
	PRIMARY KEY (MAPHONG)
)

CREATE TABLE XE
(
	MAXE CHAR(5),
	LOAIXE VARCHAR(20),
	SOCHONGOI INT,
	NAMSX INT,
	PRIMARY KEY (MAXE)
)

CREATE TABLE PHANCONG
(
	MAPC CHAR(5),
	MANV CHAR(5),
	MAXE CHAR(5),
	NGAYDI SMALLDATETIME,
	NGAYVE SMALLDATETIME,
	NOIDEN VARCHAR(25),
	PRIMARY KEY (MAPC),
	FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
	FOREIGN KEY (MAXE) REFERENCES XE(MAXE)
)


--2.1. N?m s?n xu?t c?a xe lo?i Toyota ph?i t? n?m 2006 tr? v? sau. (1.5 ?)  
--2.2. Nhân viên thu?c phòng lái xe “Ngo?i thành” ch? ???c phân công lái xe lo?i Toyota.  

ALTER TABLE XE
ADD CONSTRAINT CHK_NAMSX CHECK (YEAR(NAMSX) >= 2006)

CREATE TRIGGER PHC
ON PHANCONG
FOR UPDATE,INSERT
AS
BEGIN
	IF EXISTS (
		SELECT 1
		FROM INSERTED
		JOIN NHANVIEN ON NHANVIEN.MANV = inserted.MANV
		JOIN PHONGBAN ON PHONGBAN.MAPHONG = NHANVIEN.MAPHONG
		JOIN XE ON XE.MAXE = inserted.MAXE
		WHERE TENPHONG = N'Ngo?i thành' AND  LOAIXE != 'Toyota'
	)
	BEGIN
		PRINT('NO')	
		ROLLBACK TRANSACTION
	END
END
--3. Vi?t các câu l?nh SQL th?c hi?n các câu truy v?n sau:  
--3.1. Tìm nhân viên (MaNV,HoTen) thu?c phòng lái xe “N?i thành” ???c phân công lái lo?i xe Toyota có s? ch? ng?i là 4. (1.5 ?)  
SELECT NHANVIEN.MANV,HOTEN
FROM NHANVIEN
JOIN PHONGBAN ON PHONGBAN.MAPHONG = NHANVIEN.MAPHONG
JOIN PHANCONG ON PHANCONG.MANV = NHANVIEN.MANV
JOIN XE ON PHANCONG.MAXE = XE.MAXE
WHERE TENPHONG = N'N?i thành' AND LOAIXE = 'Toyota' AND SOCHONGOI = 4
--3.2. Tìm nhân viên(MANV,HoTen) là tr??ng phòng ???c phân công lái t?t c? các lo?i xe. (1.5 ?)  
SELECT nv.MANV,HOTEN
FROM NHANVIEN nv
JOIN PHONGBAN ON PHONGBAN.TRUONGPHONG = nv.MANV
WHERE NOT EXISTS (
	SELECT 1 
	FROM XE X
	WHERE NOT EXISTS (
		SELECT 1
		FROM PHANCONG PC
		WHERE PC.MANV = NV.MANV AND X.MAXE = PC.MAXE
	))
--3.3. Trong m?i phòng ban,tìm nhân viên (MaNV,HoTen) ???c phân công lái ít nh?t lo?i xe Toyota. (1 ?) 

SELECT NV.MANV,HOTEN, TENPHONG
FROM NHANVIEN NV
JOIN PHONGBAN ON NV.MAPHONG = PHONGBAN.MAPHONG
JOIN PHANCONG ON PHANCONG.MANV = NV.MANV
JOIN XE ON PHANCONG.MAXE = XE.MAXE
WHERE LOAIXE = 'Toyota'
GROUP BY NV.MAPHONG,NV.MANV,HOTEN
HAVING COUNT(*) = (
	SELECT MIN(COUNT(*))
	FROM NHANVIEN NV2
	JOIN PHANCONG PG ON PG.MANV = NV2.MANV
	JOIN XE X ON X.MAXE = PG.MAXE
	WHERE X.LOAIXE = 'Toyota' AND NV.MAPHONG = NV2.MAPHONG
	GROUP BY NV2.MAPHONG
)