CREATE DATABASE THITHU1
USE THITHU1
GO

CREATE TABLE TACGIA
(
	MATG CHAR(5),
	HOTEN VARCHAR(20),
	DIACHI VARCHAR(50),
	NGSINH SMALLDATETIME,
	SODT VARCHAR(15),
	PRIMARY KEY (MATG)
)

CREATE TABLE SACH
(
	MASACH CHAR(5),
	TENSACH VARCHAR(25),
	THELOAI VARCHAR(25)
	PRIMARY KEY (MASACH)
)

CREATE TABLE TACGIA_SACH
(
	MATG CHAR(5),
	MASACH CHAR(5)
	PRIMARY KEY (MATG,MASACH)
)

CREATE TABLE PHATHANH
(
	MAPH CHAR(5),
	MASACH CHAR(5),
	NGAYPH SMALLDATETIME,
	SOLUONG INT,
	NHAXUATBAN VARCHAR(20),
	PRIMARY KEY (MAPH)
)

ALTER TABLE PHATHANH
ADD CONSTRAINT FK_MASACH FOREIGN KEY (MASACH) REFERENCES SACH(MASACH)

ALTER TABLE TACGIA_SACH 
ADD CONSTRAINT FK_MATG FOREIGN KEY (MATG) REFERENCES TACGIA(MATG)

ALTER TABLE TACGIA_SACH 
ADD CONSTRAINT FK_MASACH2 FOREIGN KEY (MASACH) REFERENCES SACH(MASACH)

--2. Hi?n th?c các ràng bu?c toàn v?n sau:  
--2.1. Ngày phát hành sách ph?i l?n h?n ngày sinh c?a tác gi?. (1.5 ?)  
--2.2. Sách thu?c th? lo?i “Giáo khoa” ch? do nhà xu?t b?n “Giáo d?c” phát hành. (1.5 ?)  

CREATE TRIGGER NGPH_NGSINH
ON PHATHANH
AFTER UPDATE,INSERT
AS
BEGIN
	IF EXISTS(
		SELECT 1 
		FROM inserted
		JOIN TACGIA_SACH ON TACGIA_SACH.MASACH = inserted.MASACH
		JOIN TACGIA ON TACGIA.MATG = TACGIA_SACH.MATG
		WHERE inserted.NGAYPH <= TACGIA.NGSINH 
	)
	BEGIN
		PRINT('KO HOP LE')
		ROLLBACK TRANSACTION
	END
END

CREATE TRIGGER PH
ON SACH
FOR UPDATE,INSERT
AS
BEGIN
	IF EXISTS (
		SELECT 1 
		FROM inserted
		JOIN PHATHANH ON inserted.MASACH = PHATHANH.MASACH
		WHERE THELOAI = N'Giáo khoa' AND NHAXUATBAN != N'Giáo d?c'
	)
	BEGIN
		ROLLBACK TRANSACTION
	END
END

--3. Vi?t các câu l?nh SQL th?c hi?n các câu truy v?n sau:  
--3.1. Tìm tác gi? (MaTG,HoTen,SoDT) c?a nh?ng quy?n sách thu?c th? lo?i “V?n h?c” do nhà xu?t b?n Tr? phát hành. (1.5 ?)  
--3.2. Tìm nhà xu?t b?n phát hành nhi?u th? lo?i sách nh?t.(1.5 ?)  
--3.3. Trong m?i nhà xu?t b?n, tìm tác gi? (MaTG,HoTen) có s? l?n phát hành nhi?u sách nh?t. (1 ?)--
SELECT TACGIA.MATG,HOTEN,SODT
FROM TACGIA
JOIN TACGIA_SACH ON TACGIA_SACH.MATG = TACGIA.MATG
JOIN SACH ON TACGIA_SACH.MASACH = SACH.MASACH
JOIN PHATHANH ON SACH.MASACH = PHATHANH.MASACH
WHERE THELOAI = N'V?n h?c' AND NHAXUATBAN = N'Tr?'


SELECT TOP 1 WITH TIES NHAXUATBAN, COUNT(DISTINCT THELOAI) AS SOTL
FROM PHATHANH
JOIN SACH ON SACH.MASACH = PHATHANH.MASACH
GROUP BY NHAXUATBAN
ORDER BY SOTL DESC

SELECT NHAXUATBAN,COUNT(MASACH) AS SLPH
FROM PHATHANH
JOIN SACH ON SACH.MASACH = PHATHANH.MASACH
JOIN TACGIA_SACH ON TACGIA_SACH.MASACH = SACH.MASACH
JOIN TACGIA ON TACGIA_SACH.MATG = TACGIA.MATG
WHERE HAVING COUNT(MAPH) = (
	SELECT MASACH